#------------------------------------------------------------
# Boise State University Borah Slurm
#------------------------------------------------------------

# Cluster host and scheduler options: the defaults come from
# Graham at Compute Canada, running Slurm. Other options can
# be found in the library of snippets,
# `_includes/snippets_library`. To use one, replace options
# below with those in `_config_options.yml` from the
# library. E.g, to customise for Cirrus at EPCC, running
# PBS, we could replace the options below with those from
#
# _includes/snippets_library/EPCC_Cirrus_pbs/_config_options.yml
#
# If your cluster is not represented in the library, please
# copy an existing folder, rename it, and customize for your
# installation. Remember to keep the leading slash on the
# `snippets` variable below!

snippets: "/snippets_library/BSU_Borah_slurm"

local:
  prompt: "[user@laptop ~]$"
  bash_shebang: "#!/usr/bin/env bash"

remote:
  name: "Borah"
  login: "borah-login.boisestate.edu"
  host: "borah-login"
  node: "cpu101"
  location: "Boise State University"
  homedir: "/bsuhome"
  user: "yourUsername"
  prompt: "[yourUsername@borah-login ~]$"
  bash_shebang: "#!/usr/bin/env bash"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: "--partition=bsudfq"
  queue:
    debug: "short"
    testing: "short"
  status: "squeue"
  flag:
    user: "--me"
    interactive: ""
    histdetail: "-l -j"
    name: "-J"
    time: "-t"
    queue: "-p"
    nodes: "-N"
    tasks: "-n"
  del: "scancel"
  interactive: "dev-session"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct"

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-modules
  - 15-transferring-files
  - 16-parallel
  - 17-resources
  - 18-responsibility
